name: ovulation_tracker
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2               # must match Flutter's pin
  hooks_riverpod: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  flutter_local_notifications: ^17.2.1
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
